### ISSUE TITLE
[BUG] 500 error when accessing Web Bans page

### ISSUE THREAD

**Issue by bowtiesolutions** [bunkerity/bunkerweb#1174]
### What happened?

Attempting to access /manage/bans page is resulting in a 500 error

### How to reproduce?

Navigate to /manage/bans page

### Configuration file(s) (yaml or .env)

```YAML
DNS_RESOLVERS=10.10.0.11 10.10.0.12 1.1.1.1
HTTP_PORT=80
HTTPS_PORT=443
API_LISTEN_IP=127.0.0.1
USE_API=yes
MULTISITE=yes
UI_HOST=http://127.0.0.1:7000
SERVER_NAME=
```

### Relevant log output

```shell
[2024-05-09 22:34:45 +0000] [1160] [❌] Error handling request /manage/bans
Traceback (most recent call last):
  File "/usr/share/bunkerweb/deps/python/gunicorn/workers/gthread.py", line 282, in handle
    keepalive = self.handle_request(req, conn)
  File "/usr/share/bunkerweb/deps/python/gunicorn/workers/gthread.py", line 334, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/share/bunkerweb/deps/python/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/share/bunkerweb/ui/src/ReverseProxied.py", line 62, in __call__
    return self.app(environ, start_response)
  File "/usr/share/bunkerweb/deps/python/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/share/bunkerweb/deps/python/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/share/bunkerweb/deps/python/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/share/bunkerweb/deps/python/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/bunkerweb/deps/python/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/share/bunkerweb/deps/python/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/usr/share/bunkerweb/ui/main.py", line 2036, in bans
    instance_bans = app.config["INSTANCES"].get_bans()
  File "/usr/share/bunkerweb/ui/src/Instances.py", line 334, in get_bans
    resp, instance_bans = instance.bans()
TypeError: cannot unpack non-iterable bool object
```

### BunkerWeb version

1.5.6

### What integration are you using?

Linux

### Linux distribution (if applicable)

Ubuntu Server 22.04

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fl0ppy-d1sk** [comment]
Hello @bowtiesolutions,

Looks like I can't reproduce the issue.

Here is what I did : 
1. Install BW 1.5.6 on Ubuntu 22.04 : https://docs.bunkerweb.io/1.5.6/integrations/#linux
2. Complete the setup wizard with a valid domain
3. Access the ban page

Can you confirm that you installed the 1.5.6 version and not a dev/testing one ?

**Comment by bowtiesolutions** [comment]
Yes, have checked and confirmed 1.5.6 is in use and that both bunkerweb and nginx are held at their installed versions per the integration instructions.

I can't confirm I was able to access the bans page previously, however I was able to use 'bwcli bans' however am no longer able to (see below). 

`[2024-05-13 01:11:40] - API - ❌ - Can't send API request to http://127.0.0.1:5000/bans : Request failed: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /bans (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1ba1c83430>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-05-13 01:11:40] - CLI - ❌ - Error while executing bwcli :
Traceback (most recent call last):
  File "/usr/share/bunkerweb/cli/main.py", line 66, in <module>
    ret, err = cli.bans()
  File "/usr/share/bunkerweb/cli/CLI.py", line 246, in bans
    ret, resp = self.send_to_apis("GET", "/bans", response=True)
TypeError: cannot unpack non-iterable bool object`

**Comment by fl0ppy-d1sk** [comment]
Hello @bowtiesolutions,

Can you try again with the new 1.5.7 version ? More info here : https://docs.bunkerweb.io/1.5.7/

**Comment by bowtiesolutions** [comment]
I ended up doing a clean reinstall to 1.5.7 as the update process did not complete normally and my configuration was lost.

The bans page and bwcli are now responding normally. Running `sudo netstat -nlp` shows the API endpoint loaded now, this was not the case for 1.5.6.

 `tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      4427/nginx: master`

I suspect that /etc/nginx/api.conf was not being correctly generated or referenced in my previous installation leading to the error.
