### ISSUE TITLE
[BUG] /usr/share/bunkerweb will be deleted after ~2 Weeks 

### ISSUE THREAD

**Issue by askthewood** [bunkerity/bunkerweb#1422]
### What happened?

After 2 Weeks, Bunkerweb isn´t able to start its services, because /usr/share/bunkerweb is missing.
NO Logs File available, also /var/log/bunkerweb is also missing.

### How to reproduce?

Install fresh Bunkerweb Servcie with one reverse Proxy to a server and nothing else. 
Appeared in 1.5.7, 1.5.8, 1.5.9

### Configuration file(s) (yaml or .env)

```YAML
root@bunkerweb:/etc/bunkerweb# cat /etc/bunkerweb/variables.env
DNS_RESOLVERS=9.9.9.9 8.8.8.8 8.8.4.4
HTTP_PORT=80
HTTPS_PORT=443
API_LISTEN_IP=127.0.0.1
MULTISITE=yes
UI_HOST=http://127.0.0.1:7000
SERVER_NAME=
```

### Relevant log output

```shell
Aug 18 14:50:01 bunkerweb start.sh[319]: [2024-08-18 14:50:01 +0200] [SCHEDULER] [319] [❌] - Exception while executing job blacklist-download from plugin blacklist :
Aug 18 14:50:01 bunkerweb start.sh[319]: Traceback (most recent call last):
Aug 18 14:50:01 bunkerweb start.sh[319]:   File "/usr/share/bunkerweb/scheduler/JobScheduler.py", line 185, in __job_wrapper
Aug 18 14:50:01 bunkerweb start.sh[319]:   File "/usr/lib/python3.11/subprocess.py", line 548, in run
Aug 18 14:50:01 bunkerweb start.sh[319]:     with Popen(*popenargs, **kwargs) as process:
Aug 18 14:50:01 bunkerweb start.sh[319]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 18 14:50:01 bunkerweb start.sh[319]:   File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
Aug 18 14:50:01 bunkerweb start.sh[319]:     self._execute_child(args, executable, preexec_fn, close_fds,
Aug 18 14:50:01 bunkerweb start.sh[319]:   File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
Aug 18 14:50:01 bunkerweb start.sh[319]:     raise child_exception_type(errno_num, err_msg, err_filename)
Aug 18 14:50:01 bunkerweb start.sh[319]: FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/bunkerweb/core/blacklist/jobs/blacklist-download.py'
Aug 18 14:50:01 bunkerweb start.sh[319]: [2024-08-18 14:50:01 +0200] [SCHEDULER] [319] [ℹ️ ] - Executing job realip-download from plugin realip ...
Aug 18 14:50:01 bunkerweb start.sh[319]: [2024-08-18 14:50:01 +0200] [SCHEDULER] [319] [❌] - Exception while executing job realip-download from plugin realip :
Aug 18 14:50:01 bunkerweb start.sh[319]: Traceback (most recent call last):
Aug 18 14:50:01 bunkerweb start.sh[319]:   File "/usr/share/bunkerweb/scheduler/JobScheduler.py", line 185, in __job_wrapper
Aug 18 14:50:01 bunkerweb start.sh[319]:   File "/usr/lib/python3.11/subprocess.py", line 548, in run
Aug 18 14:50:01 bunkerweb start.sh[319]:     with Popen(*popenargs, **kwargs) as process:
Aug 18 14:50:01 bunkerweb start.sh[319]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 18 14:50:01 bunkerweb start.sh[319]:   File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
Aug 18 14:50:01 bunkerweb start.sh[319]:     self._execute_child(args, executable, preexec_fn, close_fds,
Aug 18 14:50:01 bunkerweb start.sh[319]:   File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
Aug 18 14:50:01 bunkerweb start.sh[319]:     raise child_exception_type(errno_num, err_msg, err_filename)
Aug 18 14:50:01 bunkerweb start.sh[319]: FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/bunkerweb/core/realip/jobs/realip-download.py'





root@bunkerweb:/etc/bunkerweb# systemctl status bunkerweb
● bunkerweb.service
     Loaded: not-found (Reason: Unit bunkerweb.service not found.)
     Active: active (running) since Thu 2024-08-08 17:43:57 CEST; 1 week 2 days ago
   Main PID: 126 (start.sh)
        CPU: 22min 6.276s
     CGroup: /system.slice/bunkerweb.service
             ├─  126 /bin/bash /usr/share/bunkerweb/scripts/start.sh start
             ├─  304 "nginx: master process /usr/sbin/nginx -e /var/log/bunkerweb/error.log"
             ├─  318 sudo -E -u nginx -g nginx /bin/bash -c "PYTHONPATH=/usr/share/bunkerweb/deps/python/ /usr/share/bunkerweb/scheduler/main.py --variables /etc/bunkerwe>
             ├─  319 python3 /usr/share/bunkerweb/scheduler/main.py --variables /etc/bunkerweb/variables.env
             └─10990 "nginx: worker process"

Aug 18 14:50:01 bunkerweb start.sh[319]:     with Popen(*popenargs, **kwargs) as process:
Aug 18 14:50:01 bunkerweb start.sh[319]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 18 14:50:01 bunkerweb start.sh[319]:   File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
Aug 18 14:50:01 bunkerweb start.sh[319]:     self._execute_child(args, executable, preexec_fn, close_fds,
Aug 18 14:50:01 bunkerweb start.sh[319]:   File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
Aug 18 14:50:01 bunkerweb start.sh[319]:     raise child_exception_type(errno_num, err_msg, err_filename)
Aug 18 14:50:01 bunkerweb start.sh[319]: FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/bunkerweb/core/realip/jobs/realip-download.py'
Aug 18 14:50:01 bunkerweb start.sh[319]: [2024-08-18 14:50:01 +0200] [SCHEDULER] [319] [ℹ️ ] - Successfully updated database for the job blacklist-download from plugin bla>
Aug 18 14:50:01 bunkerweb start.sh[319]: [2024-08-18 14:50:01 +0200] [SCHEDULER] [319] [ℹ️ ] - All scheduled jobs have been executed
Aug 18 14:50:01 bunkerweb start.sh[319]: [2024-08-18 14:50:01 +0200] [SCHEDULER] [319] [ℹ️ ] - Successfully updated database for the job realip-download from plugin realip
root@bunkerweb:/etc/bunkerweb#
```

### BunkerWeb version

1.5.9

### What integration are you using?

Linux

### Linux distribution (if applicable)

Debian 12

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonas0b1011001** [comment]
Same thing just happened to my installation.

@askthewood Did you get any help? Does this happen again after restoring from a backup?

**Comment by TheophileDiot** [comment]
Hi, sorry for the (very) late response. Could you provide us a bit more information about your stack (OS, Integration, etc...) ? Thank you !

**Comment by jonas0b1011001** [comment]
I'm running linux integration (Debian 12) set up using the script from https://tteck.github.io/Proxmox/. Version 1.5.9 at that time.

For me, this has been a one time event so far. After restoring from backup all has been fine.

**Comment by TheophileDiot** [comment]
This is maybe not BunkerWeb clearing the folders but something else (a script or something),. 
Does it automatically tries to update/force update BunkerWeb every now and then ?

**Comment by askthewood** [comment]
I have updated to Version 1.5.10 and didn´t happen again. So something was wrong with Version 1.5.9. If it happens again, i will let you know.
