### ISSUE TITLE
[BUG] Bunkerweb-ui wont start on RHEL 8.6

### ISSUE THREAD

**Issue by neojames** [bunkerity/bunkerweb#286]
**Description**
The following error can be found in the error log when starting bunker-ui on RHEL 8.6:

**How to reproduce**
Use RHEL 8.6, fresh build from DVD, latest updates installed.
Setup the Linux install of Bunker
Run `sudo systemctl restart bunkerweb-ui`
Run `sudo journalctl -u bunkerweb-ui --no-pager` to generate the log.

It may possible be an issue with the installed version of Python, if so I am running the default install of:

python39-3.9.7-1.module+el8.6.0+12577+62b8d0a1.x86_64 

**Logs**
```
 Starting UI
 Traceback (most recent call last):
   File "/usr/lib64/python3.6/runpy.py", line 183, in _run_module_as_main
     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
   File "/usr/lib64/python3.6/runpy.py", line 142, in _get_module_details
     return _get_module_details(pkg_main_name, error)
   File "/usr/lib64/python3.6/runpy.py", line 109, in _get_module_details
     __import__(pkg_name)
   File "/opt/bunkerweb/deps/python/flask/__init__.py", line 3, in <module>
     from werkzeug.exceptions import abort as abort
   File "/opt/bunkerweb/deps/python/werkzeug/__init__.py", line 2, in <module>
     from .test import Client as Client
   File "/opt/bunkerweb/deps/python/werkzeug/test.py", line 29, in <module>
     from .sansio.multipart import Data
   File "/opt/bunkerweb/deps/python/werkzeug/sansio/multipart.py", line 2, in <module>
     from dataclasses import dataclass
 ModuleNotFoundError: No module named 'dataclasses'
```

**Comment by myfreax** [comment]
@neojames can you tell me resolve this issue

**Comment by fl0ppy-d1sk** [comment]
@AxyFr 👀

**Comment by fl0ppy-d1sk** [comment]
ATM, it's not supported. We will postpone RHEL support to the next 1.5.X version.

**Comment by fl0ppy-d1sk** [comment]
Hello @neojames,

We now support RHEL in the last [v1.5.0-beta release](https://github.com/bunkerity/bunkerweb/releases/tag/v1.5.0-beta).

You will find some documentation [here](https://docs.bunkerweb.io/1.5.0-beta/integrations/#linux).
