### ISSUE TITLE
[BUG] Missing dependencies in bunkerity/bunkerweb-autoconf:1.4.4

### ISSUE THREAD

**Issue by Dinodanio** [bunkerity/bunkerweb#365]
**Description**
Expected behaviour:
When `bunkerweb.GENERATE_SELF_SIGNED_SSL=yes`
And NOT `bunkerweb.SELF_SIGNED_SSL_EXPIRY=300`
And NOT `bunkerweb.SELF_SIGNED_SSL_SUBJ=/CN=www.example.com`
Then a certificate should be generated
And have default values

When `bunkerweb.GENERATE_SELF_SIGNED_SSL=yes`
And `bunkerweb.SELF_SIGNED_SSL_EXPIRY=300`
And `bunkerweb.SELF_SIGNED_SSL_SUBJ=/CN=www.example.com`
Then a certificate should be generated

**How to reproduce**
Set ONLY the  `bunkerweb.GENERATE_SELF_SIGNED_SSL=yes` label on one of your webservice .

Set all 3 labels , `bunkerweb.GENERATE_SELF_SIGNED_SSL=yes` , `bunkerweb.SELF_SIGNED_SSL_EXPIRY=300`, `bunkerweb.SELF_SIGNED_SSL_SUBJ=/CN=www.example.com` on one of your webservice

**Logs**
When only one is set:
```sh
Traceback (most recent call last):
2022-11-20T14:46:33.854607102Z   File "/opt/bunkerweb/core/selfsigned//jobs/self-signed.py", line 41, in <module>
2022-11-20T14:46:33.854612238Z     ret, ret_status = generate_cert(first_server, os.getenv(first_server + "_SELF_SIGNED_SSL_EXPIRY"), os.getenv(first_server + "_SELF_SIGNED_SSL_SUBJ"))
2022-11-20T14:46:33.854614319Z   File "/opt/bunkerweb/core/selfsigned//jobs/self-signed.py", line 18, in generate_cert
2022-11-20T14:46:33.854616321Z     cmd = "openssl req -nodes -x509 -newkey rsa:4096 -keyout /opt/bunkerweb/cache/selfsigned/" + first_server + ".key -out /opt/bunkerweb/cache/selfsigned/" + first_server + ".pem -days " + days + " -subj " + subj
2022-11-20T14:46:33.854618459Z TypeError: can only concatenate str (not "NoneType") to str
```

When all 3 are set:
```sh
[2022-11-20 15:12:35] SELF-SIGNED - â�Œ - Exception while running certbot-new.py :
2022-11-20T15:12:35.585385152Z Traceback (most recent call last):
2022-11-20T15:12:35.585448817Z   File "/opt/bunkerweb/core/selfsigned//jobs/self-signed.py", line 41, in <module>
2022-11-20T15:12:35.585454936Z     ret, ret_status = generate_cert(first_server, os.getenv(first_server + "_SELF_SIGNED_SSL_EXPIRY"), os.getenv(first_server + "_SELF_SIGNED_SSL_SUBJ"))
2022-11-20T15:12:35.585457250Z   File "/opt/bunkerweb/core/selfsigned//jobs/self-signed.py", line 19, in generate_cert
2022-11-20T15:12:35.585468708Z     proc = subprocess.run(cmd.split(" "), stdin=subprocess.DEVNULL, stderr=subprocess.STDOUT)
2022-11-20T15:12:35.585470741Z   File "/usr/local/lib/python3.10/subprocess.py", line 503, in run
2022-11-20T15:12:35.585472717Z     with Popen(*popenargs, **kwargs) as process:
2022-11-20T15:12:35.585474528Z   File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
2022-11-20T15:12:35.585476381Z     self._execute_child(args, executable, preexec_fn, close_fds,
2022-11-20T15:12:35.585478174Z   File "/usr/local/lib/python3.10/subprocess.py", line 1847, in _execute_child
2022-11-20T15:12:35.585480033Z     raise child_exception_type(errno_num, err_msg, err_filename)
2022-11-20T15:12:35.585481768Z FileNotFoundError: [Errno 2] No such file or directory: 'openssl'
```

**Comment by fl0ppy-d1sk** [comment]
Hello @Dinodanio,

It should be fixed in the [v1.4.5 release](https://github.com/bunkerity/bunkerweb/releases/tag/v1.4.5).
