### ISSUE TITLE
unban error

### ISSUE THREAD

**Issue by andyoulovexy** [bunkerity/bunkerweb#387]
bash-5.1# bwcli bans
❌ Error while executing bwcli : 
Traceback (most recent call last):
  File "/opt/bunkerweb/deps/python/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bunkerweb/cli/main.py", line 46, in <module>
    ret, err = cli.bans()
  File "/opt/bunkerweb/cli/CLI.py", line 107, in bans
    ret, resp = self._send_to_apis("GET", "/bans", response=True)
  File "/opt/bunkerweb/utils/ApiCaller.py", line 23, in _send_to_apis
    sent, err, status, resp = api.request(method, url, files=files, data=data)
  File "/opt/bunkerweb/api/API.py", line 32, in request
    return True, "ok", resp.status_code, resp.json()
  File "/opt/bunkerweb/deps/python/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx</center>
</body>
</html>
: 0

**Comment by fl0ppy-d1sk** [comment]
Hello @andyoulovexy,

It should be fixed in the [v1.4.6 release](https://github.com/bunkerity/bunkerweb/releases/tag/v1.4.6).
