### ISSUE TITLE
[BUG] UI socket error processing request after the login

### ISSUE THREAD

**Issue by croghostrider** [bunkerity/bunkerweb#425]
**Description**
Hi this project is amazing. I try to run bunkerweb in Portainer, but after the login, I received a Bad Gateway 502 as an error.
I use the [example](https://github.com/bunkerity/bunkerweb/blob/master/examples/web-ui/docker-compose.yml) template.

**How to reproduce**
docker-compose.yml
```yaml
version: '3'
services:
  mybunker:
    image: bunkerity/bunkerweb:1.4.7
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - bw_data:/data
      - bw_config:/etc/nginx
      - certs:/certs
    environment:
      - SERVER_NAME=www.mydomain.ooo mydomain.ooo
      - MULTISITE=yes
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - USE_CUSTOM_HTTPS=yes
      - CUSTOM_HTTPS_CERT=/certs/live/mydomain.ooo/fullchain.pem
      - CUSTOM_HTTPS_KEY=/certs/live/mydomain.ooo/privkey.pem
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24
      - www.mydomain.ooo_USE_UI=yes
      - www.mydomain.ooo_SERVE_FILES=no
      - www.mydomain.ooo_USE_REVERSE_PROXY=yes
      - www.mydomain.ooo_REVERSE_PROXY_URL=/goldleopard26                     # replace with another url
      - www.mydomain.ooo_REVERSE_PROXY_HOST=http://myui:7000
      - www.mydomain.ooo_REVERSE_PROXY_HEADERS=X-Script-Name /goldleopard26   # replace with another url
      - www.mydomain.ooo_REVERSE_PROXY_INTERCEPT_ERRORS=no
      - www.mydomain.ooo_LIMIT_REQ_URL=/goldleopard26/plugins/upload           # replace with another url
      - www.mydomain.ooo_LIMIT_REQ_RATE=4r/s
      - www.mydomain.ooo_LIMIT_REQ_URL_1=/goldleopard26/logs                   # replace with another url
      - www.mydomain.ooo_LIMIT_REQ_RATE_1=4r/s
    labels:
      - "bunkerweb.UI"
    networks:
      - net_ui
      - net_svc
  myui:
    image: bunkerity/bunkerweb-ui:1.4.7
    depends_on:
      - myuiproxy
    volumes:
      - bw_data:/data
      - bw_config:/etc/nginx
    environment:
      - ABSOLUTE_URI=https://www.mydomain.ooo/goldleopard26/                    # replace with another url
      - DOCKER_HOST=tcp://myuiproxy:2375
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=pw1234                                           # replace with a stronger password
    networks:
      - net_ui
      - net_docker
  myuiproxy:
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
    networks:
      - net_docker
  mycertbot:
    image: certbot/dns-cloudflare
    environment:
      - DOMAINS=*.mydomain.ooo,mydomain.ooo
      - EMAIL=contact@mydomain.ooo
    volumes:
      - certs:/etc/letsencrypt
      - opt_data:/opt
    entrypoint: /bin/sh /opt/entrypoint.sh  
volumes:
  bw_data:
  bw_config:
  opt_data:
  certs:
networks:
  net_ui:
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  net_docker:
  net_svc:
```

**Logs**
bunkerweb log
```
[2023-03-19 23:49:09] ENTRYPOINT - ℹ️ - Starting BunkerWeb v1.4.7 ...
[2023-03-19 23:49:09] ENTRYPOINT - ℹ️ - Setup and check /data folder ...
[2023-03-19 23:49:09] ENTRYPOINT - ⚠️ - Looks like BunkerWeb configuration is already generated, will not generate it again
[2023-03-19 23:49:09] ENTRYPOINT - ℹ️ - Executing job scheduler ...
[2023-03-19 23:49:09] ENTRYPOINT - ℹ️ - Starting nginx ...
[2023-03-19 23:49:09] SCHEDULER - ℹ️ - Executing job scheduler ...
2023/03/19 23:49:09 [notice] 16#16: ModSecurity-nginx v1.0.2 (rules loaded inline/local/remote: 0/1825/0)
2023/03/19 23:49:09 [notice] 16#16: [INIT] Init phase started
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin customcert v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin reverseproxy v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin inject v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin bunkernet v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin headers v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin misc v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin cors v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin dnsbl v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin badbehavior v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin brotli v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin greylist v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin authbasic v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin limit v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin jobs v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin ui v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin letsencrypt v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin blacklist v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin country v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin realip v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin errors v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin gzip v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin antibot v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin selfsigned v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin modsecurity v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin clientcache v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin whitelist v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin redirect v0.1
2023/03/19 23:49:09 [notice] 16#16: [INIT] Loaded plugin php v0.1
2023/03/19 23:49:09 [error] 16#16: [INIT] Plugin bunkernet failed on init() : can't read instance id : /opt/bunkerweb/cache/bunkernet/instance.id: No such file or directory
nginx: [error] [INIT] Plugin bunkernet failed on init() : can't read instance id : /opt/bunkerweb/cache/bunkernet/instance.id: No such file or directory
2023/03/19 23:49:09 [notice] 16#16: [INIT] Init phase ended
2023/03/19 23:49:09 [notice] 16#16: using the "epoll" event method
2023/03/19 23:49:09 [notice] 16#16: nginx/1.20.2
2023/03/19 23:49:09 [notice] 16#16: built by gcc 10.3.1 20210424 (Alpine 10.3.1_git20210424) 
2023/03/19 23:49:09 [notice] 16#16: OS: Linux 5.15.102-1-pve
2023/03/19 23:49:09 [notice] 16#16: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/03/19 23:49:09 [notice] 16#16: start worker processes
2023/03/19 23:49:09 [notice] 16#16: start worker process 67
2023/03/19 23:49:09 [notice] 16#16: start worker process 68
www.mydomain.ooo XXX.XX.XXX.78 - - [19/Mar/2023:23:49:23 +0000] "GET /goldleopard26/ HTTP/2.0" 302 227 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
www.mydomain.ooo XXX.XX.XXX.78 - - [19/Mar/2023:23:49:23 +0000] "GET /goldleopard26/login HTTP/2.0" 200 997 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
www.mydomain.ooo XXX.XX.XXX.78 - - [19/Mar/2023:23:49:23 +0000] "GET /goldleopard26/js/jquery.min.js HTTP/2.0" 200 31142 "https://www.mydomain.ooo/goldleopard26/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
www.mydomain.ooo XXX.XX.XXX.78 - - [19/Mar/2023:23:49:23 +0000] "GET /goldleopard26/js/popper.min.js HTTP/2.0" 200 7235 "https://www.mydomain.ooo/goldleopard26/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
www.mydomain.ooo XXX.XX.XXX.78 - - [19/Mar/2023:23:49:23 +0000] "GET /goldleopard26/js/tsparticles.bundle.min.js HTTP/2.0" 200 47580 "https://www.mydomain.ooo/goldleopard26/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
www.mydomain.ooo XXX.XX.XXX.78 - - [19/Mar/2023:23:49:23 +0000] "GET /goldleopard26/images/BUNKERWEB-print-hd.png HTTP/2.0" 200 39964 "https://www.mydomain.ooo/goldleopard26/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
www.mydomain.ooo XXX.XX.XXX.78 - - [19/Mar/2023:23:49:23 +0000] "GET /goldleopard26/js/bootstrap.bundle.min.js HTTP/2.0" 200 23257 "https://www.mydomain.ooo/goldleopard26/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
www.mydomain.ooo XXX.XX.XXX.78 - - [19/Mar/2023:23:49:23 +0000] "GET /goldleopard26/images/BUNKERWEB-print-hd-blanc.png HTTP/2.0" 200 30346 "https://www.mydomain.ooo/goldleopard26/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
www.mydomain.ooo XXX.XX.XXX.78 - - [19/Mar/2023:23:49:23 +0000] "GET /goldleopard26/webfonts/karla/v21/qkB9XvYC6trAT55ZBi1ueQVIjQTD-JrIH2G7nytkHRyQ8p4wUje6bg.woff2 HTTP/2.0" 200 21060 "https://www.mydomain.ooo/goldleopard26/webfonts/karla.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
www.mydomain.ooo XXX.XX.XXX.78 - - [19/Mar/2023:23:49:52 +0000] "POST /goldleopard26/login HTTP/2.0" 302 289 "https://www.mydomain.ooo/goldleopard26/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
www.mydomain.ooo XXX.XX.XXX.78 - - [19/Mar/2023:23:49:52 +0000] "GET /goldleopard26/loading?next=%2Fgoldleopard26%2Fhome HTTP/2.0" 200 5959 "https://www.mydomain.ooo/goldleopard26/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
www.mydomain.ooo XXX.XX.XXX.78 - - [19/Mar/2023:23:49:53 +0000] "GET /goldleopard26/check_reloading?next=%2Fgoldleopard26%2Fhome HTTP/2.0" 200 25 "https://www.mydomain.ooo/goldleopard26/loading?next=%2Fgoldleopard26%2Fhome" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
2023/03/19 23:49:54 [error] 68#68: *22 upstream prematurely closed connection while reading response header from upstream, client: XXX.XX.XXX.78, server: www.mydomain.ooo, request: "GET /goldleopard26/home HTTP/2.0", upstream: "http://10.20.30.3:7000/goldleopard26/home", host: "www.mydomain.ooo", referrer: "https://www.mydomain.ooo/goldleopard26/loading?next=%2Fgoldleopard26%2Fhome"
www.mydomain.ooo XXX.XX.XXX.78 - - [19/Mar/2023:23:49:54 +0000] "GET /goldleopard26/home HTTP/2.0" 502 8533 "https://www.mydomain.ooo/goldleopard26/loading?next=%2Fgoldleopard26%2Fhome" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
```
bunkerweb-ui log
```    
[2023-03-19 23:49:09 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-03-19 23:49:09 +0000] [1] [INFO] Listening at: http://0.0.0.0:7000 (1)
[2023-03-19 23:49:09 +0000] [1] [INFO] Using worker: gthread
[2023-03-19 23:49:09 +0000] [6] [INFO] Booting worker with pid: 6
[2023-03-19 23:49:54 +0000] [6] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f80f72ef970>: Failed to establish a new connection: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bunkerity.com', port=443): Max retries exceeded with url: /wp-json/wp/v2/posts (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f80f72ef970>: Failed to establish a new connection: [Errno 111] Connection refused'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 343, in handle_request
    util.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 626, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/bunkerweb/ui/src/ReverseProxied.py", line 24, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/opt/bunkerweb/ui/main.py", line 287, in home

    r = get(
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.bunkerity.com', port=443): Max retries exceeded with url: /wp-json/wp/v2/posts (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f80f72ef970>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
docker-socket-proxy log
```
Proxy dockerbackend started.
Proxy dockerfrontend started.
[WARNING] 077/234908 (1) : Can't open server state file '/var/lib/haproxy/server-state': No such file or directory
[NOTICE] 077/234908 (1) : New worker #1 (7) forked
172.29.0.3:33320 [19/Mar/2023:23:49:10.234] dockerfrontend dockerbackend/dockersocket 0/0/0/3/3 200 1037 - - ---- 1/1/0/0/0 0/0 "GET /version HTTP/1.1"
172.29.0.3:33320 [19/Mar/2023:23:49:10.240] dockerfrontend dockerbackend/dockersocket 0/0/0/0/0 200 2970 - - ---- 1/1/0/0/0 0/0 "GET /v1.42/containers/json?limit=-1&all=0&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22bunkerweb.UI%22%5D%7D HTTP/1.1"
172.29.0.3:33320 [19/Mar/2023:23:49:10.241] dockerfrontend dockerbackend/dockersocket 0/0/0/0/0 200 9805 - - ---- 1/1/0/0/0 0/0 "GET /v1.42/containers/23842636f8d3e94cfa7856d1481a111abb3b60b7bcf83861f57557ea1f4a043e/json HTTP/1.1"
```

**Comment by croghostrider** [comment]
I'm not sure where the error was but now it works.

**Comment by TheophileDiot** [comment]
> I'm not sure where the error was but now it works.

Hi @croghostrider thzank you for this issue, the problem was with the bunkerity website which we were using to fetch the logs, it has now changed and in a future release we will fetch the logs a different way.

**Comment by zgurea1** [comment]
Hello, i am getting same error, how you fixed?


![image](https://user-images.githubusercontent.com/60965273/233130244-c1605669-59ef-4f16-963d-48a225307c1d.png)
![image](https://user-images.githubusercontent.com/60965273/233130433-e3175752-6e9c-46c0-9b71-0da12dc5839d.png)

**Comment by zgurea1** [comment]
I used the deafult configuration from example folder with the UI.

**Comment by TheophileDiot** [comment]
Did you change the UI container admin password to a stronger as stated in the example ? @zgurea1

**Comment by zgurea1** [comment]
Yes.

**Comment by zgurea1** [comment]
This is my docker-compose file.

version: '3'

services:

  mybunker:
    image: bunkerity/bunkerweb:1.4.8
    ports:
      - 80:8080
      - 443:8443
    # ?? read this if you use local folders for volumes ??
    # bunkerweb runs as an unprivileged user with UID/GID 101
    # don't forget to edit the permissions of the files and folders accordingly
    # example if you need to create a directory : mkdir folder && chown root:101 folder && chmod 770 folder
    # another example for existing folder : chown -R root:101 folder && chmod -R 770 folder
    # more info at https://docs.bunkerweb.io
    volumes:
      - ./bw_data:/data
      - ./bw_config:/etc/nginx
    environment:
      - SERVER_NAME=test.com
      - MULTISITE=yes
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24
      - test.com_USE_UI=yes
      - test.com_SERVE_FILES=no
      - test.com_USE_REVERSE_PROXY=yes
      - test.com_REVERSE_PROXY_URL=/kCb84nxV7VF5miDDeE7o                     # replace with another url
      - test.com_REVERSE_PROXY_HOST=http://myui:7000
      - test.com_REVERSE_PROXY_HEADERS=X-Script-Name /kCb84nxV7VF5miDDeE7o   # replace with another url
      - test.com_REVERSE_PROXY_INTERCEPT_ERRORS=no
      - test.com_LIMIT_REQ_URL=/kCb84nxV7VF5miDDeE7o/plugins/upload           # replace with another url
      - test.com_LIMIT_REQ_RATE=4r/s
      - test.com_LIMIT_REQ_URL_1=/kCb84nxV7VF5miDDeE7o/logs                   # replace with another url
      - test.com_LIMIT_REQ_RATE_1=4r/s
    labels:
      - "bunkerweb.UI"
    networks:
      - bw-ui
      - net_svc

  myui:
    image: bunkerity/bunkerweb-ui:1.4.8
    depends_on:
      - myuiproxy
    volumes:
      - ./bw_data:/data
      - ./bw_config:/etc/nginx
    environment:
      - ABSOLUTE_URI=http://test.com/kCb84nxV7VF5miDDeE7o/                    # replace with another url
      - DOCKER_HOST=tcp://myuiproxy:2375
      - ADMIN_USERNAME=YQbLQp7auNqbFi5CEh2j
      - ADMIN_PASSWORD=VJ6FUWhDYhNS7H5Snkat                                           # replace with a stronger password
    networks:
      - bw-ui
      - net_docker

  myuiproxy:
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
    networks:
      - net_docker


networks:
  bw-ui:
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  net_docker:
  net_svc:

**Comment by TheophileDiot** [comment]
@zgurea1 Are you sure that all your services start correctly ? I don't see any problem in your compose, do you have any logs ?

**Comment by zgurea1** [comment]
Hi, @TheophileDiot what can be the problem?

here is the error when i change to LOG_LEVEL=debug


[error] 43#43: *19 upstream prematurely closed connection while reading response header from upstream,
