### ISSUE TITLE
[BUG] In kubernetes access to logs not work with pod with ID not found error

### ISSUE THREAD

**Issue by lenglet-k** [bunkerity/bunkerweb#581]
**Description**
On bunkerweb-ui when i try to see the logs i have this error:

```json
{
  "message": "Pod with ID bunkerweb-wgcq6 not found!",
  "status": "ko"
}
```

The pod with bunkerweb-wgcq6 name exist

**How to reproduce**
Start a kubernetes bunkerweb stack
Show logs from the logs menu

**Logs**

HTTP CALL, 404 response:

```shell
GET https://my-fqdn.tld/logs/bunkerweb-wgcq6?from_date=1690495200000&to_date=1690495200000
```

and the response:

```json
{
  "message": "Pod with ID bunkerweb-wgcq6 not found!",
  "status": "ko"
}
```

**Comment by TheophileDiot** [comment]
Hi @lenglet-k, I'm digging up this issue to let you know that this is fixed on our end. Can you confirm ? Thank you !

**Comment by lenglet-k** [comment]
Hi, i have the same behavior in 1.5.7.

**Comment by lenglet-k** [comment]
@TheophileDiot I have test with 1.5.9.

The first problem is rbac:

We need to add `pods/log` ressource in bunkerweb clusterrole.

After i have this error:

```shell
[2024-07-23 07:45:26 +0000] [UI] [11] [❌] - Could not get logs for pod bunkerweb-v5krt
Traceback (most recent call last):
  File "/usr/share/bunkerweb/ui/main.py", line 2058, in logs_container
    kubernetes_logs = kubernetes_client.read_namespaced_pod_log(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bunkerweb/deps/python/kubernetes/client/api/core_v1_api.py", line 23957, in read_namespaced_pod_log
    return self.read_namespaced_pod_log_with_http_info(name, namespace, **kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bunkerweb/deps/python/kubernetes/client/api/core_v1_api.py", line 24076, in read_namespaced_pod_log_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bunkerweb/deps/python/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bunkerweb/deps/python/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/usr/share/bunkerweb/deps/python/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bunkerweb/deps/python/kubernetes/client/rest.py", line 244, in GET
    return self.request("GET", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bunkerweb/deps/python/kubernetes/client/rest.py", line 238, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '74c628e8-21f8-46fe-a76c-a3b418aed614', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 23 Jul 2024 07:45:26 GMT', 'Content-Length': '198'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"bunkerweb-v5krt\" not found","reason":"NotFound","details":{"name":"bunkerweb-v5krt","kind":"pods"},"code":404}
```
