### ISSUE TITLE
[FEATURE] Podman support

### ISSUE THREAD

**Issue by mwester117** [bunkerity/bunkerweb#584]
Hi,
since the 1.5.0 release Bunkerweb is no longer working on Podman, because the new scheduler container needs docker API access. Of course you can enable the Docker compatibility socket of Podman but I'm looking for a solutions without the socket. 

Is it possible to run Bunkerweb on Podman without the compatibility socket?

**Comment by mwester117** [comment]
My attempts to run the bw-docker-proxy container and scheduler under podman were not successful.

I started the socket with this command (rootless):
```
systemctl --user enable --now podman.socket
```
The socket now exists under /run/user/1001/podman/podman.sock.

Afterwards I created the containers as described in the documentation:
```
podman run -d --pod bunkerweb-pod -e CONTAINERS=1 -v /run/user/$(id -u)/podman/podman.sock:/var/run/docker.sock:ro,Z --name bw-docker-proxy docker.io/tecnativa/docker-socket-proxy:0.1
podman run -d --pod bunkerweb-pod -e DOCKER_HOST=tcp://127.0.0.1:2375 -v bw-data:/data:Z --name bw-scheduler docker.io/bunkerity/bunkerweb-scheduler:latest
```

No I get the following errors in the bw-scheduler container:
```
$ podman logs bw-scheduler 
[2023-07-31 13:01:55] - ENTRYPOINT - ℹ️ - Starting the job scheduler v1.5.0 ...
[2023-07-31 13:01:55] - ENTRYPOINT - ℹ️ - Setup and check /data folder ...
[2023-07-31 13:01:55] - ENTRYPOINT - ℹ️  - Executing scheduler ...
[2023-07-31 13:01:57] - SCHEDULER - ℹ️  - Database connection established
[2023-07-31 13:01:57] - SCHEDULER - ℹ️  - Scheduler started ...
[2023-07-31 13:01:57] - SCHEDULER - ❌ - Exception while executing scheduler : Traceback (most recent call last):
  File "/usr/share/bunkerweb/deps/python/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/share/bunkerweb/deps/python/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://127.0.0.1:2375/version

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/share/bunkerweb/deps/python/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bunkerweb/deps/python/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bunkerweb/deps/python/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/usr/share/bunkerweb/deps/python/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bunkerweb/deps/python/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 503 Server Error for http://127.0.0.1:2375/version: Service Unavailable ("b'<html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/bunkerweb/scheduler/main.py", line 212, in <module>
    api_caller.auto_setup(bw_integration=integration)
  File "/usr/share/bunkerweb/utils/ApiCaller.py", line 56, in auto_setup
    docker_client = DockerClient(
                    ^^^^^^^^^^^^^
  File "/usr/share/bunkerweb/deps/python/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bunkerweb/deps/python/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bunkerweb/deps/python/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: 503 Server Error for http://127.0.0.1:2375/version: Service Unavailable ("b'<html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>'")

[2023-07-31 13:01:57] - ENTRYPOINT - ℹ️  - Scheduler stopped

```

The bw-docker-proxy output looks like this:
```
$ podman logs bw-docker-proxy 
[WARNING] 211/130001 (1) : Can't open server state file '/var/lib/haproxy/server-state': No such file or directory
Proxy dockerbackend started.
Proxy dockerfrontend started.
[NOTICE] 211/130001 (1) : New worker #1 (6) forked
127.0.0.1:59920 [31/Jul/2023:13:00:16.782] dockerfrontend dockerbackend/dockersocket 0/0/-1/-1/0 503 213 - - SC-- 1/1/0/0/3 0/0 "GET /version HTTP/1.1"
127.0.0.1:48194 [31/Jul/2023:13:01:57.354] dockerfrontend dockerbackend/dockersocket 0/0/-1/-1/0 503 213 - - SC-- 1/1/0/0/3 0/0 "GET /version HTTP/1.1"
127.0.0.1:58992 [31/Jul/2023:13:02:45.726] dockerfrontend dockerfrontend/<NOSRV> 0/-1/-1/-1/0 403 189 - - PR-- 1/1/0/0/0 0/0 "GET / HTTP/1.1"
127.0.0.1:56972 [31/Jul/2023:13:02:55.869] dockerfrontend dockerbackend/dockersocket 0/0/-1/-1/0 503 213 - - SC-- 1/1/0/0/3 0/0 "GET /version HTTP/1.1"
```

Need assistance. A solution without using the docker compatibility socket would be fine as well.
Thanks!

**Comment by TheophileDiot** [comment]
Thank you for bringing this issue to our attention. We are pleased to inform you that this issue has been resolved in the latest version of BunkerWeb. You can update you stack to the latest version here: https://docs.bunkerweb.io/latest/.

We appreciate your feedback, which helps us improve our products, don't hesitate to open a new issue if needed.
